
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urahkxssnwxtcgamwjhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyYWhreHNzbnd4dGNnYW13amhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODM3NTAsImV4cCI6MjA2MTU1OTc1MH0.2GxGGXx-E9ACUG_8W01toMNhRGpqUMYBhlmlSvPIe4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
